filename: 'locations-sample.json'

major_grid: 500
minor_grid: 100

major_grid_color: dodgerblue
minor_grid_color: mediumblue
bg_color: darkblue
marker_done_color: slateblue
marker_deep_color: firebrick
hover_bg_color: lime
hover_fg_color: white

init_scale: 0.5
window_width: 1920
window_height: 1080

font_family: 'Helvetica Neue'
font_size: 16
font_bold: true

label_offset_x: 20
label_offset_y: -5

symbol:
    has_description: ≈

categories:
    pod:
        color: limegreen
        icon: ▣
    wreck:
        color: coral
        icon: ◩
    biome:
        color: limegreen
        icon: ▲
    interest:
        color: gold
        icon: ◼
    alien:
        color: crimson
        icon: ◈
    edge:
        color: deepskyblue
        icon: ☰
    default:
        color: darkorange
        icon: ◼

icon:
    app:        'beacon2map/resources/icon-app.png'
    reload:     'beacon2map/resources/reload-128.png'
    save:       'beacon2map/resources/save-128.png'
    reset_zoom: 'beacon2map/resources/zoom-128.png'
    grid:       'beacon2map/resources/grid-128.png'
    new:        'beacon2map/resources/add-128.png'

css:
    inspector: >
        GridpointInspector {
            background-color: RoyalBlue;
            border: 1px solid MediumBlue;
            border-radius: 8;
        }

        GridpointInspector QLineEdit, QTextEdit, QSpinBox {
            background-color: MediumBlue;
        }

json_defaults:
    reference_depth: 0